# AppVeyor configuration file for building and testing the project

# Define the build matrix
platform:
  - x64  # Use 64-bit platform

# Define the build script
build_script:
  - cmd: dotnet restore  # Restore NuGet packages
  - cmd: dotnet build --configuration Release  # Build the project

# Define the test script
test_script:
  - cmd: dotnet test  # Run tests